language: generic 
sudo: required

services:
    - docker

before_install:
    - sudo apt-get install sshpass
    - docker build -t juannitram/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true juannitram/docker-react npm run test

deploy:
    provider: script
    script: sshpass -p $SERVER_PASSWORD ssh deploy@34.69.229.232 -o stricthostkeychecking=no bash deploy.sh
    