language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t juannitram/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true juannitram/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "sa-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-sa-east-1-191230746171"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id:
        secure: "Encrypted <access-key-id>=$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "Encypted <secret-access-key>=AWS_SECRET_KEY"


