language: generic 
sudo: required

services:
    - docker

before_install:
    - sudo apt-get install sshpass
    - docker build -t juannitram/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true juannitram/docker-react npm run test

deploy:
    provider: script
    script: bash scripts/deploy.sh
    