language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t juannitram/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true juannitram/docker-react npm run test

deploy:
    provider: gae
    keyfile: "client-secret.json"
    project: "vm-server-instance"
    on: master