language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t juannitram/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true juannitram/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    access_key_id:
        secure: "AKIASZBR5TY57TFJIWQ3"
    secret_access_key:
        secure: "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"
    region: "sa-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-sa-east-1-191230746171"