language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t juannitram/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true juannitram/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    edge: true
    access_key_id: "AKIASZBR5TY5VIFAGZEL"
    secret_access_key: "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"
    region: "sa-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-sa-east-1-191230746171"